[Discord]
ImagesText = RF Dimension
DiscordID = 1441867609476956240
;Your Discord DeveloperID

Button1URL = https://www.google.com/
Button1String = Play Now

Button2URL = https://discord.gg/sfEyM2we8A
Button2String = Join Discord