;DO NOT CHANGE THE PARAMETER ORDER LIKE (%d), (%s), (%.2f), (%u), etc !!!
;Maximum String 64
[HVNLanguage]
tooltip_additional = "Item General Info"
tooltip_throw = "Throw"
tooltip_infinite = "Infinite Use"
tooltip_radius = "Radius"
tooltip_recoveryrate = "Recovery Rate"
tooltip_amount_required = "Amount Required :"
tooltip_tower_install_time = "Installation Time"
guildpoint_info = "Guild Point Information"
guildpoint_accumulated = "Guild accumulated Point(s) :"
guildpoint_weekly = "Guild weekly Point(s) :"
guildpoint_usercontribution = "Guild weekly contribution Point(s) :"
guild_noguild = "No Guild"
guildskill_title = "Guild Skill"
guildskill_passive = "Passive"
guildskill_castmaster = "Guild Master"
guildskill_castmastersenator = "Guild Master & Senator"
guildskill_target = "One's self & one's guild"
guildskill_effect = "GuildSkill Effects"
guildskill_upg = "Upgrade Skill"
guildskill_upg_next_cost = "Next Level Upgrade Cost"
guildskill_hpfpsp = "Max HP/FP/SP"
codex_title = "Collect Inventory"
codex_effect = "Collection Effect"
codex_progress = "Progress"
codex_filter_title = "Filter Codex to Show"
codex_filter_showcomplete = "Show Complete Collection"
codex_register_title = "Collection Registration"
codex_list_name = "Collection"
upgrader_title = "Upgrade Options"
upgrader_enhancer = "Item Enhancer"
upgrader_protector = "Item Protector"
upgrader_help = "How it works"
pvpinfo_title = "Today PVP Information"
pvpinfo_warinfo = "LastWar Information"
pvpinfo_warcb = "Chip Breaker :"
pvpinfo_warcbkiller = "Chip Breaker Killer :"
currency_cashcoin = "Cash Coin"
currency_guildpoint = "Guild Points"
currency_bp_exp = "Battlepass Exp Points"
currency_bp_premium = "Battlepass Exp Points"
skillinfo_playerdebuff = "[Player Debuff Limitation]"
skillinfo_wardebuff = "[War Time Restriction]"

;Support Fontawesome Icons
;Maximum String 256
;Mini Description support Coloring, Tooltip Description not support, both support Icon.
[HVNDescription]
guildskill_tooltip_desc = "\uE07E A guild-wide energy surge amplifies power, fortification, and resource flow across all members, unifying your forces with enhanced combat efficiency. Click to open the Guild Skill Menu."
guildskill_tooltip_desc1 = <font-color="#9AF0FC">\uE07E Guild Skill</font> provides a buff to you and your guild members.
guildskill_tooltip_desc2 = <font-color="#31FF39">To use the skill</font> hover over the skill icon and <font-color="#31FF39">right click</font> on it.
codex_tooltip_desc = "Gather items from across the galaxy to complete Codex collections. Each collection grants a unique passive effect, strengthening your combat performance and resonance with advanced technologies. Click to open the Codex and track your progress."
codex_confirmation = "Would you like to collect and register the item? Items are consumed when registering for collection."
option_fps_desc = "Toggle FPS display at bottom-left corner."
option_pvp_desc = "Show kill feed (who killed whom) during PvP battles."
option_shake_desc = "Enables shaking effect during explosions or powerful hits."
option_popup_desc1 = Disables side popups like <font-color="#00ff15">"Upgrade Enhancer / Protector Notification"</font>.
option_popup_desc2 = "Broadcast and critical system alerts will still appear as popups."
upgrader_desc1 = "If you have an Item Enhancer or Protector in your inventory, turning it ON or OFF will affects every upgrade attempt."
upgrader_desc2 = " - Increases the chance of a successful upgrade."
upgrader_desc3 = " - Protects your item from downgrade or destruction."
upgrader_desc4 = <font-color="#31FF39">Only works if you have the item in inventory.</font>
window_lock = <font-color="#99D9FF">Window Lock / Unlock (ESC)</font>
playerdebuff_trade = "You are restricted from throwing an item for %d Seconds"
playerdebuff_ground = "You are restricted from taking a ground item for %d Seconds"
playerdebuff_throw = "You are restricted from trading for %d Seconds"
wardebuff_exp_avail = "EXP is available from all monsters"
wardebuff_exp_not_avail = "EXP is available only from certain monsters"
wardebuff_loot_avail = "Loot is available from all monsters"
wardebuff_loot_not_avail = "Loot is available only from certain monsters"

[HVNResponse]
general_received_success = "You just received %s."
general_received_premium_days = "You just received %u day(s) of Premium Service."
general_received_premium_days_note = "You just received %u day(s) of Premium Service. Consider logging out to activate the effects."
general_fail_received = "Failed to receive %s."
general_fail_received_premium_days = "Failed to receive %u day(s) of Premium Service."
battlepass_claim_success = "Reward claimed successfully!"
battlepass_invalid_reward_type = "Battlepass : Invalid reward type. Please try again."
battlepass_premium_only = "Battlepass : This reward is only available for premium users."
battlepass_level_not_reached = "Battlepass : You haven't reached the required level to claim this reward."
battlepass_reward_locked = "Battlepass : You haven't unlocked this reward yet."
battlepass_already_claimed = "Battlepass : You have already claimed this reward."
battlepass_send_failed = "Battlepass : There was a problem sending your reward. Please contact support."
battlepass_update_failed_code = "Battlepass : There was a problem updating your reward status (%d). Please try again later."
battlepass_send_failed_code = "Battlepass : There was a problem sending your reward (%d). Please contact support."
battlepass_item_not_found = "Battlepass : The reward item could not be found. Please try again later."
battlepass_send_failed_code2 = "Battlepass : There was a problem sending your reward (%d). Please contact support."
battlepass_invalid_reward_level = "Battlepass : Invalid Reward [%d] Level [%d]."
battlepass_unknown_error = "Battlepass : Unknown Error %s. [%d] Level [%d]."
gskill_upgrade_success = "GuildSkill : Skill upgrade successful for %s."
gskill_not_in_guild = "GuildSkill : Player is not in a guild."
gskill_only_master_upgrade = "GuildSkill : Only the Guild Master can upgrade the skill."
gskill_invalid_upgrade = "GuildSkill : Invalid skill upgrade attempt."
gskill_max_level = "GuildSkill : Skill cannot be upgraded anymore (maximum level reached)."
gskill_not_enough_points_required = "GuildSkill : Not enough Guild Points to upgrade the skill. Required: %s."
gskill_not_enough_points = "GuildSkill : Not enough Guild Points to upgrade the skill. Check the website for more information."
gskill_update_failed = "GuildSkill : Failed to update guild data. Please try again later or contact the administrator."
gskill_upgrade_error = "GuildSkill : Problem upgrading skill (%s) Error (%d). Please contact support."
gskill_cast_success = "GuildSkill : Skill cast successful for %s."
gskill_not_in_guild2 = "GuildSkill : Player is not in a guild."
gskill_only_master_cast = "GuildSkill : Only the Guild Master can cast this skill."
gskill_invalid_cast = "GuildSkill : Invalid skill cast attempt."
gskill_level_zero_cast = "GuildSkill : Skill cannot be cast at level 0."
gskill_cast_required_items = "GuildSkill : Required %d of %s to cast Guild Skill %s."
gskill_cast_missing_required_item = "GuildSkill : Required item to cast skill. Check website for more information."
gskill_cast_wait_time = "GuildSkill : You need to wait (%d) second(s) to cast (%s)."
gskill_only_master_or_senator_cast = "GuildSkill : Only the Guild Master or Guild Senator can cast this skill."
gskill_cast_error = "GuildSkill : Problem casting skill (%s) Error (%d). Please contact support."
codex_update_success = "Codex progress updated successfully!"
codex_invalid_player_state = "Item Codex Failure : Invalid player state."
codex_trade_blocked = "Item Codex Failure : Can't codex whilst trading."
codex_already_collected = "Item Codex Failure : Already collected."
codex_stunned_blocked = "Item Codex Failure : Can't codex item while stunned."
codex_item_not_exist = "Item Codex Failure : Item does not exist."
codex_impossible = "Item Codex Failure : Impossible to codex."
codex_item_locked = "Item Codex Failure : Can't codex item while locked."
codex_invalid_item = "Item Codex Failure : Invalid item."
codex_update_failed = "Item Codex Failure : Problem updating codex progress (%d). Please contact support."
codex_item_consume_failed = "Item Codex Failure : Failed to consume item. Contact support for more information."
codex_unknown_error = "Item Codex Failure : Unknown error (%d). Please contact support."
npc_wait_time = "You need to wait (%d) second(s)."
npc_premium = "Sorry, you need Premium Service to access this NPC."
npc_vip = "Sorry, this NPC is exclusive to VIP members or donators."
npc_notavailable = "Sorry, this NPC is currently unavailable or locked. Please come back later."
npc_level_required = "Sorry, you need level (%d) to access this NPC."
npc_unknown_error = "ItemTrade Related : Unknown error (%d)."
potion_notwartime = "You can't use this potion during WarTime."
potion_wartime = "You can only use this potion during WarTime."
buffer_success = "Buffer : Buff added."
buffer_fail_map = "Buffer : Not in map area."
buffer_fail_die = "Buffer : You're dead. Please revive first."
buffer_fail_siege = "Buffer : You're on Siege Mode. Please UnSiege first."
buffer_fail_gvg = "Buffer : Sorry, GvG in progress."
broadcast_delay_map = "Broadcast : You need to wait (%d) seconds to use Megaphone Broadcast [Map]."
broadcast_delay_race = "Broadcast : You need to wait (%d) seconds to use Megaphone Broadcast [Race]."
broadcast_delay_global = "Broadcast : You need to wait (%d) seconds to use Megaphone Broadcast [Global]."
broadcast_level_map = "Broadcast : You need level [%d] to use Megaphone Broadcast [Map]."
broadcast_level_race = "Broadcast : You need level [%d] to use Megaphone Broadcast [Race]."
broadcast_level_global = "Broadcast : You need level [%d] to use Megaphone Broadcast [Global]."
tower_race = "GUARD TOWER : Tower belongs to another race."