;DO NOT CHANGE THE PARAMETER ORDER LIKE (%d), (%s), (%.2f), (%u), etc !!!
;Maximum String 64
[HVNLanguage]
tooltip_additional = "一般情報"
tooltip_throw = "丟棄"
tooltip_infinite = "無限藥水"
tooltip_radius = "半徑"
tooltip_recoveryrate = "恢復率"
guildpoint_info = "公會點數資訊"
guildpoint_accumulated = "公會累積點數："
guildpoint_weekly = "公會週點數："
guildpoint_usercontribution = "公會每週貢獻點數 :"
guild_noguild = "沒有公會"
guildskill_title = "公會技能"
guildskill_passive = "被動"
guildskill_castmaster = "公會會長"
guildskill_castmastersenator = "公會會長或委員會"
guildskill_target = "自己與公會成員"
guildskill_effect = "公會技能效果"
guildskill_upg = "升級技能"
guildskill_upg_next_cost = "下一級升級消耗"
guildskill_hpfpsp = "最大HP/FP/SP"
codex_title = "努霸司聖典"
codex_effect = "努霸司聖典效果"
codex_progress = "努霸司聖典進度"
codex_filter_title = "篩選效果"
codex_filter_showcomplete = "顯示全部收藏"
codex_register_title = "登記"
codex_list_name = "收藏"
upgrader_title = "特殊升級選項"
upgrader_enhancer = "物品強化"
upgrader_protector = "物品保護"
upgrader_help = "如何使用"
tooltip_amount_required = "所需數量"
tooltip_tower_install_time = "架設時間"
pvpinfo_title = "今日PVP資訊"
pvpinfo_warinfo = "最近一次種族戰資訊"
pvpinfo_warcb = "晶片破壞者:"
pvpinfo_warcbkiller = "晶片破壞者殺手:"
currency_cashcoin = "商城點數"
currency_guildpoint = "公會點數"
currency_bp_exp = "戰鬥通行證經驗值"
currency_bp_premium = "激活高級戰鬥通行證"
skillinfo_playerdebuff = "[玩家減益限制]"
skillinfo_wardebuff = "[戰時限制]"

;Support Fontawesome Icons
;Maximum String 256
;Mini Description support Coloring, Tooltip Description not support, both support Icon.
[HVNDescription]
guildskill_tooltip_desc = "全公會能量湧動，提升所有成員的力量、防禦力和資源流動。增強戰鬥效率，統一你的部隊。點選開啟公會技能選單。"
guildskill_tooltip_desc1 = <font-color="#9AF0FC">公會技能</font> 可以給你和你的公會會員一些增益效果。
guildskill_tooltip_desc2 = <font-color="#31FF39">運用技能</font> 將滑鼠停留在技能圖示上，然後 <font-color="#31FF39">右鍵點擊</font> 技能圖示。
codex_tooltip_desc = "收集來自尼日太陽系各地的物品，完成聖典收藏。每套收藏都會賦予你獨特的被動效果，增強你的戰鬥能力，並提升你與先進科技的契合度。點擊即可開啟聖典，追蹤你的進度"
codex_confirmation = "您是否要登記該物品？物品會在登記時被消耗掉。"
option_fps_desc = "在左下角切換幀率顯示。"
option_pvp_desc = "在 PvP 戰鬥中顯示擊殺訊息（例如誰擊殺了誰）。"
option_shake_desc = "可在爆炸或強力撞擊時產生震動效果。"
option_popup_desc1 = 停用側邊彈出窗口，例如<font-color="#00ff15">「物品強化/物品保護」</font>。
option_popup_desc2 = "廣播和關鍵系統警報仍將以彈出視窗的形式顯示。"
upgrader_desc1 = "如果你的物品欄裡有物品強化器/保護器，開啟/關閉它們會影響你每次升級。"
upgrader_desc2 = " - 用於提高升級幾率。"
upgrader_desc3 = " - 用於保護您的物品免遭降級/銷毀。"
upgrader_desc4 = <font-color="#31FF39">只有當你的物品欄中有該物品時才有效。</font>
window_lock = <font-color="#99D9FF">視窗鎖定/解鎖 ESC</font>
playerdebuff_trade = "你被限制在 %d 秒內無法丟棄物品。"
playerdebuff_ground = "你被限制在 %d 秒內無法拾取地面物品。"
playerdebuff_throw = "您已被限制交易 %d 秒"
wardebuff_exp_avail = "所有怪物都可獲得經驗值。"
wardebuff_exp_not_avail = "經驗值只能從特定的怪物身上獲得。"
wardebuff_loot_avail = "所有怪物身上都會掉落物品。"
wardebuff_loot_not_avail = "戰利品只能從特定怪物身上獲得。"

[HVNResponse]
general_received_success = "您已收到 %s "
general_received_premium_days = "您剛剛獲得了 %u 天的高級服務"
general_received_premium_days_note = "您剛剛獲得了 %u 天的高級服務，請考慮登出以啟動效果。"
general_fail_received = "未收到 %s "
general_fail_received_premium_days = "未收到 %u 天的高級服務"
battlepass_claim_success = "獎勵已成功領取！"
battlepass_invalid_reward_type = "戰鬥通行證：獎勵類型無效，請重試。"
battlepass_premium_only = "戰鬥通行證：此獎勵僅限高級用戶獲得。"
battlepass_level_not_reached = "戰鬥通行證：您尚未達到領取此獎勵所需的等級。"
battlepass_reward_locked = "戰鬥通行證：您尚未解鎖此獎勵。"
battlepass_already_claimed = "戰鬥通行證：您已領取此獎勵。"
battlepass_send_failed = "戰鬥通行證：您的獎勵發放出現問題，請聯絡客服。"
battlepass_update_failed_code = "戰鬥通行證：更新您的獎勵狀態時出現問題（%d）。請稍後再試。"
battlepass_send_failed_code = "戰鬥通行證：您的獎勵（%d）發放出現問題。請聯絡客服。"
battlepass_item_not_found = "戰鬥通行證：未找到獎勵物品。請稍後再試。"
battlepass_send_failed_code2 = "戰鬥通行證：您的獎勵（%d）發放出現問題。請聯絡客服。"
battlepass_invalid_reward_level = "戰鬥通行證：獎勵無效 [%d] 等級 [%d]"
battlepass_unknown_error = "戰鬥通行證：未知錯誤 %s。 [%d] 等級 [%d]"
gskill_upgrade_success = "公會技能: %s 技能升級成功。"
gskill_not_in_guild = "公會技能：玩家未加入任何公會。"
gskill_only_master_upgrade = "公會技能：只有公會會長才能升級此技能。"
gskill_invalid_upgrade = "公會技能：技能升級嘗試無效。"
gskill_max_level = "公會技能：該技能無法再升級（已達到最高等級）。"
gskill_not_enough_points_required = "公會技能：沒有足夠的公會點數來升級該技能，所需點數：%s。"
gskill_not_enough_points = "公會技能：公會點數不足以升級此技能，請查看網站以了解更多資訊。"
gskill_update_failed = "公會技能：公會資料更新失敗，請稍後重試或聯絡管理員。"
gskill_upgrade_error = "公會技能：升級技能時有問題 (%s) 錯誤 (%d)。請聯絡客服。"
gskill_cast_success = "公會技能：%s 技能施放成功。"
gskill_not_in_guild2 = "公會技能：玩家未加入任何公會。"
gskill_only_master_cast = "公會技能 : 只有公會會長才能施放此技能。"
gskill_invalid_cast = "公會技能：無效的技能施放嘗試。"
gskill_level_zero_cast = "公會技能：0級時無法施放此技能。"
gskill_cast_required_items = "公會技能：需要 %d 個 %s 來施展公會技能[%s]。"
gskill_cast_missing_required_item = "公會技能：施放此技能所需的物品，詳情請查看網站。"
gskill_cast_wait_time = "公會技能 : 您需要等待 (%d) 秒才能施放 (%s) 。"
gskill_only_master_or_senator_cast = "公會技能：只有公會會長或委員會才能施放此技能。"
gskill_cast_error = "GuildSkill：施放技能時有問題 (%s) 錯誤 (%d)。請聯絡客服。"
codex_update_success = "努霸司聖典進度已成功更新！"
codex_invalid_player_state = "聖典錯誤：玩家狀態無效。"
codex_trade_blocked = "努霸司聖典錯誤：交易時無法進行聖典蒐集。"
codex_already_collected = "努霸司聖典錯誤：已收集。"
codex_stunned_blocked = "努霸司聖典錯誤：在眩暈狀態下無法使用聖典收集物品。"
codex_item_not_exist = "努霸司聖典錯誤：物品不存在。"
codex_impossible = "努霸司聖典錯誤：無法收集。"
codex_item_locked = "努霸司聖典錯誤：物品被鎖定時無法將其加入聖典。"
codex_invalid_item = "努霸司聖典錯誤：物品無效。"
codex_update_failed = "努霸司聖典錯誤：更新聖典進度（%d）時出現問題。請聯絡客服。"
codex_item_consume_failed = "努霸司聖典錯誤：物品使用失敗，請聯絡客服以取得更多資訊。"
codex_unknown_error = "努霸司聖典錯誤：未知錯誤（%d）。請聯絡客服。"
npc_wait_time = "您需要等待 (%d) 秒。"
npc_premium = "抱歉，您需要高級會員服務才能使用此NPC。"
npc_vip = "抱歉，此NPC僅限達指定金額贊助者使用。"
npc_notavailable = "抱歉，目前該NPC不可用/已鎖定，請稍後再來。"
npc_level_required = "抱歉，您需要達到 (%d) 等級才能存取此 NPC"
npc_unknown_error = "物品交易相關：未知錯誤 (%d)"
potion_notwartime = "戰爭時無法使用此藥水。"
potion_wartime = "此藥水只能在戰爭時期使用。"
buffer_success = "Buffer : 增益狀態已套用"
buffer_fail_map = "Buffer : 不在施展範圍內"
buffer_fail_die = "Buffer : 您死了，請先復活"
buffer_fail_siege = "Buffer : 您目前處於砲座模式，請先解除砲座模式。"
buffer_fail_gvg = "Buffer : 抱歉，GvG正在進行中。"
broadcast_delay_map = "廣播系統：使用擴音器廣播需要等待 (%d) 秒 [地圖]"
broadcast_delay_race = "廣播系統：使用擴音器廣播需要等待 (%d) 秒 [種族]"
broadcast_delay_global = "廣播系統：使用擴音器廣播需要等待 (%d) 秒 [全服]"
broadcast_level_map = "廣播系統：你需要達到等級 [%d] 才能使用擴音器廣播 [地圖]"
broadcast_level_race = "廣播系統：你需要達到等級 [%d] 才能使用擴音器廣播 [種族]"
broadcast_level_global = "廣播系統：你需要達到等級 [%d] 才能使用擴音器廣播 [全服]"
tower_race = "守衛塔：這座塔屬於其它種族。"